#!/usr/bin/env python
"""Tables and paired tests over the judged free-text runs.

    uv run python scripts/15_freetext_stats.py                   # MedMCQA arms
    uv run python scripts/15_freetext_stats.py --dataset miriad  # parity arms

Reads ``results/freetext/judged/`` and writes
``results/freetext/summary_<dataset>.{md,json}``: the per-arm table, the
paired deltas with sign-flip permutation p-values and bootstrap intervals, and
the both-orders pairwise counts where a pair was judged that way. REPORT.md
quotes these tables; regenerate rather than edit them.

No GPU, no judge: everything here is arithmetic over committed JSON.
"""

from __future__ import annotations

from fvr.config import bootstrap_env, load_config  # isort: skip

import argparse
import json
import sys
from pathlib import Path

from rich.console import Console
from rich.markdown import Markdown

from fvr.eval.freetext import PAIRS_BY_DATASET, RunNaming
from fvr.report.freetext import (
    JudgedArm,
    PairedScoreDelta,
    PairwiseRecord,
    arms_table,
    deltas_table,
    load_judged,
    load_pairwise,
    paired_delta,
    score_interval,
)

console = Console()


def mcq_accuracy(results: Path, arm: str, seed: int) -> float | None:
    """The same arm's MCQ accuracy at the reference seed, if it was run."""
    path = results / "runs" / f"{arm}_seed{seed}.json"
    if not path.is_file():
        return None
    return float(json.loads(path.read_text(encoding="utf-8"))["accuracy"])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", choices=sorted(PAIRS_BY_DATASET), default="medmcqa")
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--stat-seed", type=int, default=0, help="bootstrap/permutation RNG")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="score fully-correct-or-not (majority grade 2 -> 1, else 0) instead of the 0-1 mean",
    )
    args = parser.parse_args()

    project = load_config()
    paths = bootstrap_env(project)
    seed = args.seed if args.seed is not None else project.seed
    naming = RunNaming(args.dataset, seed)
    judged_dir = paths.results / "freetext" / "judged"

    arms: dict[str, JudgedArm] = {}
    for path in sorted(judged_dir.glob(naming.glob)):
        if path.stem.startswith("pairwise_"):
            continue
        arm = load_judged(path, strict=args.strict)
        arms[naming.arm_of(path.stem)] = arm
    if not arms:
        console.print(f"[red]No judged runs under {judged_dir} for {args.dataset}.[/]")
        return 1

    intervals = {name: score_interval(arm, seed=args.stat_seed) for name, arm in arms.items()}

    extra_cols: dict[str, dict[str, str]] = {}
    mcq: dict[str, float] = {}
    for name in arms:
        accuracy = mcq_accuracy(paths.results, name, seed)
        if accuracy is not None:
            mcq[name] = accuracy
            extra_cols[name] = {"MCQ accuracy": f"{100 * accuracy:.1f}%"}

    deltas: list[PairedScoreDelta] = []
    pairwise: dict[tuple[str, str], PairwiseRecord] = {}
    mcq_deltas: dict[tuple[str, str], str] = {}
    for arm_a, arm_b in PAIRS_BY_DATASET[args.dataset]:
        if arm_a not in arms or arm_b not in arms:
            console.print(f"  [dim]{arm_a} - {arm_b}: not both judged yet, skipping[/]")
            continue
        deltas.append(paired_delta(arms[arm_a], arms[arm_b], seed=args.stat_seed))
        pair_file = judged_dir / f"{naming.pairwise_stem(arm_a, arm_b)}.json"
        if pair_file.is_file():
            pairwise[(arm_a, arm_b)] = load_pairwise(pair_file)
        if arm_a in mcq and arm_b in mcq:
            mcq_deltas[(arm_a, arm_b)] = f"{100 * (mcq[arm_a] - mcq[arm_b]):+.1f}"

    table_arms = arms_table(list(arms.values()), intervals, extra=extra_cols)
    table_deltas = deltas_table(
        deltas, pairwise, extra=mcq_deltas, extra_name="MCQ Δ" if mcq_deltas else ""
    )
    flag = " --strict" if args.strict else ""
    markdown = (
        f"<!-- generated by scripts/15_freetext_stats.py --dataset {args.dataset}{flag}; "
        "do not edit -->\n\n"
        f"{table_arms}\n\n{table_deltas}\n"
    )

    suffix = "_strict" if args.strict else ""
    out_md = paths.results / "freetext" / f"summary_{args.dataset}{suffix}.md"
    out_json = out_md.with_suffix(".json")
    out_md.write_text(markdown, encoding="utf-8")
    out_json.write_text(
        json.dumps(
            {
                "dataset": args.dataset,
                "seed": seed,
                "stat_seed": args.stat_seed,
                "scoring": "strict: majority grade 2 -> 1, else 0"
                if args.strict
                else "graded: mean of 0/1/2 over judge seeds, /2",
                "arms": {
                    name: {
                        "n": arm.n,
                        "mean_score": round(arm.mean_score, 4),
                        "ci95": [round(intervals[name].low, 4), round(intervals[name].high, 4)],
                        "judge_sd": arm.judge_sd,
                        "unparseable": arm.unparseable,
                        "max_new_tokens": arm.max_new_tokens,
                        "capped_answers": arm.capped_answers,
                        "mcq_accuracy": mcq.get(name),
                    }
                    for name, arm in arms.items()
                },
                "deltas": [d.as_json() for d in deltas],
                "pairwise": [r.as_json() for r in pairwise.values()],
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    console.print(Markdown(markdown))
    console.print(f"\nwritten  [cyan]{out_md}[/]  [cyan]{out_json}[/]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
